import { SVGName } from "@/src/constants/SVGIcon";
import moment from "moment";

type CategoriesValues = { svg: SVGName; name: string; route: string }[];

export const Settings: CategoriesValues = [
  {
    svg: "account-how-to-play",
    name: "Sweepstakes Rules",
    route: "/(stack)/about/sweepstakes-rules",
  },
  {
    svg: "account-terms",
    name: "Terms & Conditions",
    route: "/(stack)/about/terms-and-conditions",
  },
  {
    svg: "account-privacy",
    name: "Privacy Policy",
    route: "/(stack)/about/privacy-policy",
  },
  {
    svg: "account-support",
    name: "Contact Support",
    route: "/contact-support",
  },
];

export const AUTHSettings: CategoriesValues = [
  {
    svg: "account-redeem",
    name: "Redeem",
    route: "/(stack)/redeem",
  },
  {
    svg: "account-me",
    name: "My Account",
    route: "/(stack)/user-profile",
  },
  {
    svg: "account-transactions",
    name: "Transactions",
    route: "/(stack)/transactions",
  },
  {
    svg: "account-how-to-play",
    name: "Sweepstakes Rules",
    route: "/(stack)/about/sweepstakes-rules",
  },
  {
    svg: "account-terms",
    name: "Terms & Conditions",
    route: "/(stack)/about/terms-and-conditions",
  },
  {
    svg: "account-privacy",
    name: "Privacy Policy",
    route: "/(stack)/about/privacy-policy",
  },
  {
    svg: "account-terms",
    name: "Terms & Conditions",
    route: "/(stack)/about/terms-and-conditions",
  },
  // {
  //   svg: "account-faq",
  //   name: "FAQs",
  //   route: "/about/faq",
  // },
  {
    svg: "account-support",
    name: "Contact Support",
    route: "/(stack)/contact-support",
  },
];

type CountriesTypes = {
  code: string;
  name: string;
};

export const Countries: CountriesTypes[] = [
  { code: "AFG", name: "Afghanistan" },
  { code: "ALB", name: "Albania" },
  { code: "DZA", name: "Algeria" },
  { code: "AND", name: "Andorra" },
  { code: "AGO", name: "Angola" },
  { code: "ATG", name: "Antigua" },
  { code: "ARG", name: "Argentina" },
  { code: "ARM", name: "Armenia" },
  { code: "AUS", name: "Australia" },
  { code: "AUT", name: "Austria" },
  { code: "AZE", name: "Azerbaijan" },
  { code: "BHS", name: "Bahamas" },
  { code: "BHR", name: "Bahrain" },
  { code: "BGD", name: "Bangladesh" },
  { code: "BRB", name: "Barbados" },
  { code: "BLR", name: "Belarus" },
  { code: "BEL", name: "Belgium" },
  { code: "BLZ", name: "Belize" },
  { code: "BEN", name: "Benin" },
  { code: "BTN", name: "Bhutan" },
  { code: "BOL", name: "Bolivia" },
  { code: "BIH", name: "Bosnia" },
  { code: "BWA", name: "Botswana" },
  { code: "BRA", name: "Brazil" },
  { code: "BRN", name: "Brunei" },
  { code: "BGR", name: "Bulgaria" },
  { code: "BFA", name: "Burkina" },
  { code: "BDI", name: "Burundi" },
  { code: "CPV", name: "Cabo Verde" },
  { code: "KHM", name: "Cambodia" },
  { code: "CMR", name: "Cameroon" },
  { code: "CAN", name: "Canada" },
  { code: "CAF", name: "Central African" },
  { code: "TCD", name: "Chad" },
  { code: "CHL", name: "Chile" },
  { code: "CHN", name: "China" },
  { code: "COL", name: "Colombia" },
  { code: "COM", name: "Comoros" },
  { code: "COG", name: "Congo" },
  { code: "COK", name: "Cook Islands" },
  { code: "CRI", name: "Costa Rica" },
  { code: "CIV", name: "Côte d'Ivoire" },
  { code: "HRV", name: "Croatia" },
  { code: "CUB", name: "Cuba" },
  { code: "CYP", name: "Cyprus" },
  { code: "CZE", name: "Czechia" },
  { code: "PRK", name: "Democratic People's Republic of Korea" },
  { code: "COD", name: "Democratic Republic of the Congo" },
  { code: "DNK", name: "Denmark" },
  { code: "DJI", name: "Djibouti" },
  { code: "DMA", name: "Dominica" },
  { code: "DOM", name: "Dominican Republic" },
  { code: "ECU", name: "Ecuador" },
  { code: "EGY", name: "Egypt" },
  { code: "SLV", name: "El Salvador" },
  { code: "GNQ", name: "Equatorial Guinea" },
  { code: "ERI", name: "Eritrea" },
  { code: "EST", name: "Estonia" },
  { code: "SWZ", name: "Eswatini" },
  { code: "ETH", name: "Ethiopia" },
  { code: "FRO", name: "Faroe Islands" },
  { code: "FJI", name: "Fiji" },
  { code: "FIN", name: "Finland" },
  { code: "FRA", name: "France" },
  { code: "GAB", name: "Gabon" },
  { code: "GMB", name: "Gambia" },
  { code: "GEO", name: "Georgia" },
  { code: "DEU", name: "Germany" },
  { code: "GHA", name: "Ghana" },
  { code: "GRC", name: "Greece" },
  { code: "GRD", name: "Grenada" },
  { code: "GTM", name: "Guatemala" },
  { code: "GIN", name: "Guinea" },
  { code: "GNB", name: "Guinea-Bissau" },
  { code: "GUY", name: "Guyana" },
  { code: "HTI", name: "Haiti" },
  { code: "HND", name: "Honduras" },
  { code: "HUN", name: "Hungary" },
  { code: "ISL", name: "Iceland" },
  { code: "IND", name: "India" },
  { code: "IDN", name: "Indonesia" },
  { code: "IRN", name: "Iran" },
  { code: "IRQ", name: "Iraq" },
  { code: "IRL", name: "Ireland" },
  { code: "ISR", name: "Israel" },
  { code: "ITA", name: "Italy" },
  { code: "JAM", name: "Jamaica" },
  { code: "JPN", name: "Japan" },
  { code: "JOR", name: "Jordan" },
  { code: "KAZ", name: "Kazakhstan" },
  { code: "KEN", name: "Kenya" },
  { code: "KIR", name: "Kiribati" },
  { code: "KWT", name: "Kuwait" },
  { code: "KGZ", name: "Kyrgyzstan" },
  { code: "LAO", name: "Lao People's Democratic Republic" },
  { code: "LVA", name: "Latvia" },
  { code: "LBN", name: "Lebanon" },
  { code: "LSO", name: "Lesotho" },
  { code: "LBR", name: "Liberia" },
  { code: "LBY", name: "Libya" },
  { code: "LTU", name: "Lithuania" },
  { code: "LUX", name: "Luxembourg" },
  { code: "MDG", name: "Madagascar" },
  { code: "MWI", name: "Malawi" },
  { code: "MYS", name: "Malaysia" },
  { code: "MDV", name: "Maldives" },
  { code: "MLI", name: "Mali" },
  { code: "MLT", name: "Malta" },
  { code: "MHL", name: "Marshall Islands" },
  { code: "MRT", name: "Mauritania" },
  { code: "MUS", name: "Mauritius" },
  { code: "MEX", name: "Mexico" },
  { code: "FSM", name: "Micronesia (Federated States of)" },
  { code: "MCO", name: "Monaco" },
  { code: "MNG", name: "Mongolia" },
  { code: "MNE", name: "Montenegro" },
  { code: "MAR", name: "Morocco" },
  { code: "MOZ", name: "Mozambique" },
  { code: "MMR", name: "Myanmar" },
  { code: "NAM", name: "Namibia" },
  { code: "NRU", name: "Nauru" },
  { code: "NPL", name: "Nepal" },
  { code: "NLD", name: "Netherlands" },
  { code: "NZL", name: "New Zealand" },
  { code: "NIC", name: "Nicaragua" },
  { code: "NER", name: "Niger" },
  { code: "NGA", name: "Nigeria" },
  { code: "NIU", name: "Niue" },
  { code: "MKD", name: "North Macedonia" },
  { code: "NOR", name: "Norway" },
  { code: "OMN", name: "Oman" },
  { code: "PAK", name: "Pakistan" },
  { code: "PLW", name: "Palau" },
  { code: "PAN", name: "Panama" },
  { code: "PNG", name: "Papua New Guinea" },
  { code: "PRY", name: "ParaguayGuinea" },
  { code: "PER", name: "Peru" },
  { code: "PHL", name: "Philippines" },
  { code: "POL", name: "Poland" },
  { code: "PRT", name: "Portugal" },
  { code: "QAT", name: "Qatar" },
  { code: "KOR", name: "Republic of Korea" },
  { code: "MDA", name: "Republic of Moldova" },
  { code: "ROU", name: "Romania" },
  { code: "RUS", name: "Russian Federation" },
  { code: "RWA", name: "Rwanda" },
  { code: "KNA", name: "Saint Kitts" },
  { code: "LCA", name: "Saint Lucia" },
  { code: "VCT", name: "Saint Vincent and the Grenadines" },
  { code: "WSM", name: "Samoa" },
  { code: "SMR", name: "San Marino" },
  { code: "STP", name: "Sao Tome and Principe" },
  { code: "SAU", name: "Saudi Arabia" },
  { code: "SEN", name: "Senegal" },
  { code: "SRB", name: "Serbia" },
  { code: "SYC", name: "Seychelles" },
  { code: "SLE", name: "Sierra Leone" },
  { code: "SGP", name: "Singapore" },
  { code: "SVK", name: "Slovakia" },
  { code: "SVN", name: "Slovenia" },
  { code: "SLB", name: "Solomon Islands" },
  { code: "SOM", name: "Somalia" },
  { code: "ZAF", name: "South Africa" },
  { code: "SSD", name: "South Sudan" },
  { code: "ESP", name: "Spain" },
  { code: "LKA", name: "Sri Lanka" },
  { code: "SDN", name: "Sudan" },
  { code: "SUR", name: "Suriname" },
  { code: "SWE", name: "Sweden" },
  { code: "CHE", name: "Switzerland" },
  { code: "SYR", name: "Syrian Arab Republic" },
  { code: "TJK", name: "Tajikistan" },
  { code: "THA", name: "Thailand" },
  { code: "TLS", name: "Timor-Leste" },
  { code: "TGO", name: "Togo" },
  { code: "TKL", name: "Tokelau" },
  { code: "TON", name: "Tonga" },
  { code: "TTO", name: "Trinidad and Tobago" },
  { code: "TUN", name: "Tunisia" },
  { code: "TUR", name: "Turkey" },
  { code: "TKM", name: "Turkmenistan" },
  { code: "TUV", name: "Tuvalu" },
  { code: "UGA", name: "Uganda" },
  { code: "UKR", name: "Ukraine" },
  { code: "ARE", name: "United Arab Emirates" },
  { code: "GBR", name: "United Kingdom of Great Britain and Northern Ireland" },
  { code: "TZA", name: "United Republic of Tanzania" },
  { code: "USA", name: "United States of America" },
  { code: "URY", name: "Uruguay" },
  { code: "UZB", name: "Uzbekistan" },
  { code: "VUT", name: "Vanuatu" },
  { code: "VEN", name: "Venezuela" },
  { code: "VNM", name: "Viet Nam" },
  { code: "YEM", name: "Yemen" },
  { code: "ZMB", name: "Zambia" },
  { code: "ZWE", name: "Zimbabwe" },
];

export const Gender: string[] = ["Male", "Female", "Other"];

export interface USState {
  id?: number;
  name: string;
  code?: string;
  abbreviation: string;
  territory: boolean;
  contiguous: boolean;
}

export const USStates: USState[] = [
  {
    name: "Alabama",
    abbreviation: "AL",
    territory: false,
    contiguous: true,
  },
  {
    name: "Alaska",
    abbreviation: "AK",
    territory: false,
    contiguous: false,
  },
  {
    name: "American Samoa",
    abbreviation: "AS",
    territory: true,
    contiguous: false,
  },
  {
    name: "Arizona",
    abbreviation: "AZ",
    territory: false,
    contiguous: true,
  },
  {
    name: "Arkansas",
    abbreviation: "AR",
    territory: false,
    contiguous: true,
  },
  {
    name: "California",
    abbreviation: "CA",
    territory: false,
    contiguous: true,
  },
  {
    name: "Colorado",
    abbreviation: "CO",
    territory: false,
    contiguous: true,
  },
  {
    name: "Connecticut",
    abbreviation: "CT",
    territory: false,
    contiguous: true,
  },
  {
    name: "Delaware",
    abbreviation: "DE",
    territory: false,
    contiguous: true,
  },
  {
    name: "District Of Columbia",
    abbreviation: "DC",
    territory: false,
    contiguous: true,
  },
  {
    name: "Florida",
    abbreviation: "FL",
    territory: false,
    contiguous: true,
  },
  {
    name: "Georgia",
    abbreviation: "GA",
    territory: false,
    contiguous: true,
  },
  {
    name: "Guam",
    abbreviation: "GU",
    territory: true,
    contiguous: false,
  },
  {
    name: "Hawaii",
    abbreviation: "HI",
    territory: false,
    contiguous: false,
  },
  {
    name: "Idaho",
    abbreviation: "ID",
    territory: false,
    contiguous: true,
  },
  {
    name: "Illinois",
    abbreviation: "IL",
    territory: false,
    contiguous: true,
  },
  {
    name: "Indiana",
    abbreviation: "IN",
    territory: false,
    contiguous: true,
  },
  {
    name: "Iowa",
    abbreviation: "IA",
    territory: false,
    contiguous: true,
  },
  {
    name: "Kansas",
    abbreviation: "KS",
    territory: false,
    contiguous: true,
  },
  {
    name: "Kentucky",
    abbreviation: "KY",
    territory: false,
    contiguous: true,
  },
  {
    name: "Louisiana",
    abbreviation: "LA",
    territory: false,
    contiguous: true,
  },
  {
    name: "Maine",
    abbreviation: "ME",
    territory: false,
    contiguous: true,
  },
  {
    name: "Maryland",
    abbreviation: "MD",
    territory: false,
    contiguous: true,
  },
  {
    name: "Massachusetts",
    abbreviation: "MA",
    territory: false,
    contiguous: true,
  },
  {
    name: "Michigan",
    abbreviation: "MI",
    territory: false,
    contiguous: true,
  },
  {
    name: "Minnesota",
    abbreviation: "MN",
    territory: false,
    contiguous: true,
  },
  {
    name: "Mississippi",
    abbreviation: "MS",
    territory: false,
    contiguous: true,
  },
  {
    name: "Missouri",
    abbreviation: "MO",
    territory: false,
    contiguous: true,
  },
  {
    name: "Montana",
    abbreviation: "MT",
    territory: false,
    contiguous: true,
  },
  {
    name: "Nebraska",
    abbreviation: "NE",
    territory: false,
    contiguous: true,
  },
  {
    name: "Nevada",
    abbreviation: "NV",
    territory: false,
    contiguous: true,
  },
  {
    name: "New Hampshire",
    abbreviation: "NH",
    territory: false,
    contiguous: true,
  },
  {
    name: "New Jersey",
    abbreviation: "NJ",
    territory: false,
    contiguous: true,
  },
  {
    name: "New Mexico",
    abbreviation: "NM",
    territory: false,
    contiguous: true,
  },
  {
    name: "New York",
    abbreviation: "NY",
    territory: false,
    contiguous: true,
  },
  {
    name: "North Carolina",
    abbreviation: "NC",
    territory: false,
    contiguous: true,
  },
  {
    name: "North Dakota",
    abbreviation: "ND",
    territory: false,
    contiguous: true,
  },
  {
    name: "Northern Mariana Islands",
    abbreviation: "MP",
    territory: true,
    contiguous: false,
  },
  {
    name: "Ohio",
    abbreviation: "OH",
    territory: false,
    contiguous: true,
  },
  {
    name: "Oklahoma",
    abbreviation: "OK",
    territory: false,
    contiguous: true,
  },
  {
    name: "Oregon",
    abbreviation: "OR",
    territory: false,
    contiguous: true,
  },
  {
    name: "Palau",
    abbreviation: "PW",
    territory: true,
    contiguous: false,
  },
  {
    name: "Pennsylvania",
    abbreviation: "PA",
    territory: false,
    contiguous: true,
  },
  {
    name: "Puerto Rico",
    abbreviation: "PR",
    territory: true,
    contiguous: false,
  },
  {
    name: "Rhode Island",
    abbreviation: "RI",
    territory: false,
    contiguous: true,
  },
  {
    name: "South Carolina",
    abbreviation: "SC",
    territory: false,
    contiguous: true,
  },
  {
    name: "South Dakota",
    abbreviation: "SD",
    territory: false,
    contiguous: true,
  },
  {
    name: "Tennessee",
    abbreviation: "TN",
    territory: false,
    contiguous: true,
  },
  {
    name: "Texas",
    abbreviation: "TX",
    territory: false,
    contiguous: true,
  },
  {
    name: "Utah",
    abbreviation: "UT",
    territory: false,
    contiguous: true,
  },
  {
    name: "Vermont",
    abbreviation: "VT",
    territory: false,
    contiguous: true,
  },
  {
    name: "Virgin Islands",
    abbreviation: "VI",
    territory: true,
    contiguous: false,
  },
  {
    name: "Virginia",
    abbreviation: "VA",
    territory: false,
    contiguous: true,
  },
  {
    name: "Washington",
    abbreviation: "WA",
    territory: false,
    contiguous: true,
  },
  {
    name: "West Virginia",
    abbreviation: "WV",
    territory: false,
    contiguous: true,
  },
  {
    name: "Wisconsin",
    abbreviation: "WI",
    territory: false,
    contiguous: true,
  },
  {
    name: "Wyoming",
    abbreviation: "WY",
    territory: false,
    contiguous: true,
  },
];

export const schedulePopup = () => {
  const day = moment().day();

  switch (day) {
    case 0:
      return "Starter Pack";
    case 1:
      return "Weekly Booster";
    case 2:
      return "Cheapy Tuesday";
    case 3:
      return "High Roller Pack";
    case 4:
    case 6:
      return "Dragon Roller";
    case 5:
      return "TGIF Offer";
  }
};

export type IDTypesValue = {
  value: string;
  label: string;
};

export const IDTypes: IDTypesValue[] = [
  {
    value: "DRIVERS_LICENSE",
    label: "Driver's License",
  },
];
